### ISSUE TITLE
very easy to cheat

### ISSUE THREAD

**Issue by dominictarr** [felipebueno/lizardspock#1]
It would be very easy to fork this app and allow cheat so that you waited for your opponents move before sending your move.

However, you could prevent this, and make a _cryptographically secure_ version of rock-paper-scissors-lizard-spock by using a [commitment protocol](https://en.wikipedia.org/wiki/Commitment_scheme)

Basically, instead of sending your move, you'd send `hmac(move, nonce)` and then once you receive your opponent's commitment then you'd send the `nonce` and your opponent would then be unable to change their move without a hash collision.

That would get you a fair two player game, but if you wanted to prove that you won to a third party (say for a tournament, etc) then you'd need signatures too.

going further down this road you get to things like [cryptographically secure poker](https://en.wikipedia.org/wiki/Mental_poker) which is pretty cool!

**Comment by felipebueno** [comment]
Hi, @dominictarr 

Thanks for pointing that but this game was made just to get developers started with Sneer's PartnerSession api so we had to keep it (very) simple.

And thanks for the links. Very interesting read indeed! :)
